---
title: "Spatial Changes in Drug Overdose Deaths Over Tim"
shorttitle: "Paper"
abstract: "Drug epidemics have consistiently reflected the broader social context they take place in. Rates of use, overdoses, and arrests, can help indicate the significance of policies, culture shifts, and various other movements. In light of the National Adderall Shortage, Expansion of Fentanyl Networks, as well as the pandemic, This paper examines the rates of drug overdose at a state level over the past five years. Keywords:Overdose, Regional Death Rates, Drug Related Deaths"
keywords: [keyword1, keyword2]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/chicago-parenthetical.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

This project aims to answer the following: How do rates of Drug Induced Deaths DID overtime vary by state? Drug epidemics have consistiently reflected the broader social context they take place in. Rates of use, overdoses, and arrests, can help indicate the significance of policies, culture shifts, and various other movements. In light of the National Adderall Shortage, Expansion of Fentanyl Networks, as well as the pandemic, This paper examines the rates of drug overdose at a state level over the past five years. Utilizing quantitative methods, this research aims to contribute to deviance and crime studys that rely upon geospatial analyses to substantiate community and public health issues, in this case, drug epidemics

# Background

# Data and Methods

# Results

# Conclusions
